# Generated by Django 4.2 on 2025-01-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collections_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="status",
            field=models.CharField(max_length=50),
        ),
    ]
